### ISSUE TITLE
Cuepoint video length calculation does not take into account timezone offset

### ISSUE THREAD

**Issue by azack** [soton-ecs-2014-gdp-12/videogular-cuepoints#3]
The line
```var videoLength = API.totalTime.getTime() / 1000;```
at https://github.com/soton-ecs-2014-gdp-12/videogular-cuepoints/blob/master/cuepoints.js#L27
does not take into account time zones.  This can be corrected by adjusting the line to read:

```var videoLength = (API.totalTime.getTime()/1000 - (API.totalTime.getTimezoneOffset() * 60));```

You can see similar logic inside videogular at https://github.com/2fdevs/videogular/blob/master/app/scripts/com/2fdevs/videogular/plugins/controls.js#L364

**Comment by HarryCutts** [comment]
This is a duration, so timezone shouldn't be relevant, surely? Or am I missing something about durations in JavaScript?

**Comment by azack** [comment]
@HarryCutts It threw me off too.  I might be wrong but I suspect its because the duration / the totalTime property is being stored in a Date object.  getTime() returns milliseconds since Jan 1 1970... GMT.   So, for example,  if I create a date object with a small value like 60 seconds, but in my local time zone that's ahead of GMT, and then call getTime() on it, I get a negative value.

**Comment by HarryCutts** [comment]
So this actually causing a bug? What is it?

**Comment by azack** [comment]
@HarryCutts In my case, the cuepoints don't display in the scrub bar correctly - they all appear at the very beginning of the video.  The reason is that calcLeft() returns a bogus value because the videoLength is wrong.

**Comment by chewett** [comment]
Thats very true, I will try and look into fixing this in the coming weeks however we have a number of uni deadlines currently. A pull with the noted changes would be awesome, or a pull request is welcome :)

**Comment by azack** [comment]
It looks like this is fixed by that merge and can be closed
