### ISSUE TITLE
Error: undefined is not a function (evaluating 'API.totalTime.getTime()')

### ISSUE THREAD

**Issue by cmelian** [soton-ecs-2014-gdp-12/videogular-cuepoints#4]
Hi,

There is a typo in cuepoints.js : 
`API.totalTime.getTime(). `

Should be :
`API.totalTime`

Regards.

**Comment by lifeofbrian** [comment]
I just submitted a pull request for this tweak.

**Comment by HarryCutts** [comment]
Apologies for the slowness on this, we've been busy graduating :). I'll try and test the patch next week.

**Comment by lifeofbrian** [comment]
@HarryCutts - not a problem.. congrats and thanks for your great plugin to videogular!

**Comment by HarryCutts** [comment]
The fix has been merged and a new release made. Thanks for your help.
